### ISSUE TITLE
On Clients top overview page

### ISSUE THREAD

**Issue by martapiekarska** [fidlabs/filplus-dashboard-webapp#3]
General overview of Clients on top of the page, then the table. 
- In the table columns:  Client ID||DataCap Received||DataCap Used|| Number of SPs ||Deals Made||Allocator Used||Allocator ID||Address
- Add a top level overview like on Filecoin Pulse: 
![image](https://github.com/user-attachments/assets/75230410-a896-470b-9f0e-738d20a07422)

**Comment by tplocic20** [comment]
@smooth-operator So, as discussed on Slack - those new 4 overview params will be added to the `getVerifiedClients` API call.

This is the data model we are getting from the `getVerifiedCLients`

`{
  id: number
  addressId: string
  address: string
  retries: number
  auditTrail: string
  name: string
  orgName: string
  region: string
  website: string
  industry: string
  initialAllowance: string
  allowance: string
  verifierAddressId: string
  createdAtHeight: number
  issueCreateTimestamp: any
  createMessageTimestamp: number
  verifierName: string
  dealCount: any
  providerCount: any
  topProvider: any
  receivedDatacapChange: string
  usedDatacapChange: string
  allowanceArray: []
}`

We need to show this data, and this are the fields I think are right
- ClientID (`addressID`)
- DataCap Received (`initialAllowance`)
- DataCap Used (`usedDatacapChange`)
- Number of SPs (`providerCount`) - but often it's null
- Deals Made (`dealCount`) - also often null
- Allocator Used / Allocator ID - This one I don't get fully, is this the allocator that is "handling" this user? @martapiekarska 
-  Address (`address`)

**Comment by tplocic20** [comment]
@smooth-operator 
For the DataCap Received/Used - I've seen some differences. This field was called "Over last two weeks" - so Maybe that's the difference

**Comment by smooth-operator** [comment]
> @smooth-operator For the DataCap Received/Used - I've seen some differences. This field was called "Over last two weeks" - so Maybe that's the difference

Yes, that's datacap used in the last 2 weeks only. We don't return the total datacap used in the api response, i can be computed as **initialAllowance - allowance**

**Comment by smooth-operator** [comment]
> Number of SPs (providerCount) - but often it's null
Deals Made (dealCount) - also often nul

The fields are correct. The counts being null is a problem that will be fixed as we move to using only claims. 

The problem comes from the fact that each line in the clients table doesn't represent a client address, but rather a unique client address / verifier address pair. The counts are based on deal info, and a deal is not directly linked on chain to a verifier so we need to infer which verifier allocated the datacap used in the deal. This part of the code doesn't seem to work very reliably so many of the deals are not allocated to a verifier and that messes up those counts.
